ALTER TABLE "Site" ADD COLUMN "artworkGroups" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Site" ADD COLUMN "artworkTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Site" ADD COLUMN "artworkLocations" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Site" ADD COLUMN "mediumPresets" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Site" ADD COLUMN "sizePresets" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
